name: github-packags-docker
description: Build and publish Docker container images to GitHub Packages
author: Kasumi Hanazuki <kasumi@rollingapple.net>
inputs:
  token:
    description: GitHub token used when pushing image to GHCR
    default: ${{ github.token }}
  owner:
    description: Container registry owner
    default: ${{ github.repository_owner }}
  name:
    description: Name of the container image
    required: true
  tag:
    description: Name of the tag (image won't get published if not specified)
    required: false
  build_context:
    description: Path to the build context
    default: .
    required: false
  file:
    description: Path to Dockerfile
    required: false
  platforms:
    description: List of platforms to build image (comma-delimited)
    default: linux/amd64
    required: false
outputs:
  image_id:
    description: ID of the built image
runs:
  using: node12
  main: dist/index.js
