name: Package

on:
  push:
    branches:
      - '*'

jobs:
  package:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build && npm run pack
    - name: Publish
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{github.token}}
      run: |
        case "$GITHUB_REF" in
          refs/heads/master) deploy_branch=latest ;;
          *) exit 1 ;;
        esac

        git config user.email 'github-actions@exapi.co'
        git config user.name 'GitHub Actions'
        git config credential.https://github.com/.helper '! f() { echo username=x-access-token; echo password=$GITHUB_TOKEN; };f'

        subject=$(git show --no-patch --pretty='format:%s')

        if git fetch --depth=1 origin "$deploy_branch"; then
          git worktree add -f -b "$deploy_branch" publish FETCH_HEAD
          cd publish
        else
          git worktree add -f --detach publish
          cd publish
          git checkout --orphan "$deploy_branch"
          git rm -rf .
        fi

        rsync -Rav --delete ../{action.yml,dist,.github/workflows/tag.yaml} ./

        git add -A
        git commit --allow-empty -m "$subject" -m "Built-From: ${GITHUB_SHA}"
        git push origin "$deploy_branch"
