name: Package

on:
  push:
    branches:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install
      run: |
        npm install
    - name: Build
      run: |
        npm run build && npm run pack
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: |
        case "$GITHUB_REF" in
          refs/heads/master) deploy_branch=latest ;;
          *) exit 1 ;;
        esac

        git config user.email 'automate@hanazuki.dev'
        git config user.name 'automate'

        subject=$(git show --no-patch --pretty='format:%s')

        if git fetch --depth=1 origin "$deploy_branch"; then
          git worktree add -f -b "$deploy_branch" publish FETCH_HEAD
          cd publish
        else
          git worktree add -f --detach publish
          cd publish
          git checkout --orphan "$deploy_branch"
          git rm -rf .
        fi

        (cd ..; rsync -Rav --delete {action.yml,dist,.github/workflows/tag.yaml} ./publish/)

        git add -A
        git commit --allow-empty -m "$subject" -m "Built-From: ${GITHUB_SHA}"
        git push origin "$deploy_branch"
