name: Update tag

on:
  push:
    tags:
      - 'v*'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ensure packaged tree
      run: |
        test -d dist || {
          echo "::error::Not a packaged tree"
          exit 1
        }
    - name: Update tag
      run: |
        version=${GITHUB_REF#refs/tags/v}
        major=${version%%.*}

        git config user.email 'automate@hanazuki.dev'
        git config user.name 'automate'

        git tag -f "v${major}"
        git push origin --tags
